### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kmehant** [saivittalb/weloss-frontend#1]
- [x] Meet Section: Collaborators can fill a form and schedule meets. The meet will be listed. Users can show if interested. The interested count will be shown to the collaborator.

- [x] Main: User enters preferences and projects are shown. Each project will have a description, tech stack, org name, stars count, the link of resources to learn, the link of resources provided by collaborators, slack channel, possible mentors.

- [x] Communities: Section containing a list of communities where users can join. Communities will be manually added from trusted sources. It contains the detail of communities. Shows a list of communities.

- [x] Opportunities Section: Contains FOSS contests and programs like GSoC with details and relevant stories.

- [x] Learn: User enters preferences (language, tech stack, tech domain), and a list of tutorials, guides, articles, and relevant courses are shown.

- [x] Forum: Official discord server for addressing all questions.

- [x] Newsletter: Sending a newsletter every month briefing major details from all sections.

- [x] Reputation: Working on an algorithm that automatically tracks issues, commits, PRs, etc made by the user like Hacktoberofest.

- [x] BlogPost: A list of blogs that are dynamically updated which are written by fellow FOSS developers may be related to their contribution experience but not limited to. These blogs are submitted and reviewed by volunteers.

- [x] User Profile

- [ ] Login Screen
